project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "Propaganda and Public Diplomacy"
  site-url: "https://courses.aozturk.net"
  navbar:
    left:
      - href: index.qmd
        text: Overview
      - href: readings.qmd
        text: Weekly Readings

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true